import type { Metadata } from "next";

import QuoteNav from "@/components/QuoteNav";
import "./globals.css";

export const metadata: Metadata = {
  title: "Fairy Quotes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <div className="h-screen flex flex-col">
          <div className="flex-grow flex flex-row overflow-hidden justify-center">
            <div className="flex-shrink-0 w-1/4 p-4 overflow-y-auto">
              <QuoteNav />
            </div>
            <main className="flex-1 flex flex-col overflow-y-auto p-4">
              {children}
            </main>
          </div>
          <div className="bg-gray-800 p-4">
            s ❤️ a písní na rtech vytvořil{" "}
            <a
              className="font-medium text-blue-600 underline dark:text-blue-500 hover:no-underline"
              href="mailto:skovajsa.s@gmail.com"
            >
              Štěpán Skovajsa
            </a>
          </div>
        </div>
      </body>
    </html>
  );
}
